# Generated by Django 6.0.5 on 2026-05-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_project_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
