# Generated by Django 6.0.5 on 2026-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_task_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('예정', '예정'), ('진행 중', '진행 중'), ('완료', '완료')], default='예정', max_length=20),
        ),
    ]
